Add scaleFactor to CLI | Add .cancelRecording function
wulkano/aperture-node pull request #20
Opened 2021-05-14 13:57 UTC by dac09

## What does it do?
- Adds scale factor argument to CLI and node function
- Adds new `cancelRecording` function to stop and discard the recording

Fixes #18
Please note I haven't had a chance to test this out yet on this version, but I am using something similar in my older fork

2021-05-14 14:02 UTC, sindresorhus requested changes

2021-05-14 14:02 UTC, sindresorhus commented on index.d.ts
> +     Useful when recording retina screens, or for resizing the recorded video
Needs to document the default value. Use the correct TS doc syntax.

2021-05-14 14:02 UTC, sindresorhus commented on index.js
> +  recorderTimeout = null
Use `undefined`.

2021-05-14 14:02 UTC, sindresorhus commented on index.d.ts
> +    cancelRecording: () => void;
I just noticed that we have been very inconsistent with naming. I think this should be `cancel()`. I'll fix the other methods when this is merged.

2021-05-14 14:02 UTC, sindresorhus commented on index.js
> +    if (this.recorder !== undefined) {
Use early-return.

2021-05-14 14:02 UTC, sindresorhus commented on index.js
> +      this.recorderTimeout && clearTimeout(this.recorderTimeout)
Use `if-statement`.

2021-05-14 14:02 UTC, sindresorhus commented
You need to update the readme too.

2021-05-14 14:03 UTC, sindresorhus commented
For next time, the `.cancel()` addition should have been a separate pull request.

2021-05-14 14:25 UTC, dac09 commented on index.d.ts
> +     */
Is it worth adding prettier to the project? Would avoid these sort of issues.

2021-05-14 14:35 UTC, sindresorhus commented on index.d.ts
> +     */
Nah. prettier does indeed make things more consistent, but IMHO also less readable and ugly.

2021-10-04 06:18 UTC, sindresorhus commented on index.js
> +  recorderTimeout = undefined
```suggestion
  _recorderTimeout = undefined
```

2021-10-04 06:20 UTC, sindresorhus commented on index.d.ts
> +    Cancels a recording, if it was started
```suggestion
    Cancels a recording if it was running.
```

2021-10-04 06:21 UTC, sindresorhus commented
Readme and index.d.ts should be fully in sync.

2021-10-04 06:21 UTC, sindresorhus commented on index.d.ts
> +    @default 1
```suggestion
    The scale factor to use.

    The actual height and width of the capture will be multiplied by this number to create the height and width of the output.

    @default 1
```

2021-12-14 23:49 UTC, closed without merging